site_name: BurkeQL Tutorial
site_url: https://burke1791.github.io/burkeql-db/
repo_url: https://github.com/burke1791/burkeql-db/

nav:
  - Home: index.md
  - 'Project Roadmap': 00-intro/project-plan.md
  - 'Basic CLI':
    - Intro: 01-basic-cli/intro.md
    - Flex: 01-basic-cli/flex.md
    - Bison: 01-basic-cli/bison.md
    - 'Putting It Together': 01-basic-cli/putting-it-together.md
  - 'Abstract Syntax Trees':
    - Intro: 02-ast/intro.md
    - 'AST Interface': 02-ast/ast-interface.md
    - 'AST Implementation': 02-ast/ast-implementation.md
    - 'Parser Refactor': 02-ast/parser-refactor.md
    - 'Parser Interface': 02-ast/parser-interface.md
    - 'Putting It Together': 02-ast/putting-it-together.md
  - 'The Database Page':
    - 'Page Structure': 03-db-page/page-structure.md
  - 'Data Persistence':
    - Intro: 04-data-persistence/01-intro.md
    - 'Config File': 04-data-persistence/02-config-file.md
    - 'Loading Config': 04-data-persistence/03-loading-config.md
    - 'DB File Interface': 04-data-persistence/04-file-interface.md
    - 'DB Page Interface': 04-data-persistence/05-page-interface.md
    - 'DB Page Implementation': 04-data-persistence/06-page-implementation.md
    - 'Parser Refactor - Insert': 04-data-persistence/07-parser-refactor-insert.md
    - 'Serializing and Inserting Data': 04-data-persistence/08-serializing-and-inserting-data.md
  - 'Selecting Data':
    - 'Parser Refactor - Select': 05-selecting-data/01-parser-refactor-select.md
    - 'The SQL Analyzer': 05-selecting-data/02-the-sql-analyzer.md
    - 'Buffer Pool': 05-selecting-data/03-buffer-pool.md
    - 'Table Scan': 05-selecting-data/04-table-scan.md

theme: readthedocs