site_name: BurkeQL Tutorial
site_url: https://burke1791.github.io/burkeql-db/
repo_url: https://github.com/burke1791/burkeql-db/

nav:
  - Home: index.md
  - 'Project Plan': 00-intro/project-plan.md
  - 'Basic CLI':
    - Intro: 01-basic-cli/intro.md
    - Flex: 01-basic-cli/flex.md
    - Bison: 01-basic-cli/bison.md
    - 'Putting It Together': 01-basic-cli/putting-it-together.md
  - 'Abstract Syntax Trees':
    - Intro: 02-ast/intro.md
    - 'AST Interface': 02-ast/ast-interface.md
    - 'AST Implementation': 02-ast/ast-implementation.md
    - 'Parser Refactor': 02-ast/parser-refactor.md
    - 'Parser Interface': 02-ast/parser-interface.md
    - 'Putting It Together': 02-ast/putting-it-together.md
  - 'The Database Page':
    - 'Page Structure': 03-db-page/page-structure.md
  - 'Data Persistence':
    - Intro: 04-data-persistence/intro.md
    - 'Config File': 04-data-persistence/config-file.md
    - 'DB File Interface': 04-data-persistence/file-interface.md
    - 'DB Page Interface': 04-data-persistence/page-interface.md
    - 'DB Page Implementation': 04-data-persistence/page-implementation.md
    - 'Parser Update - Insert': 04-data-persistence/parser-insert.md
    - 'Insert Logic': 04-data-persistence/insert-logic.md
    - 'Putting It Together': 04-data-persistence/putting-it-together.md

theme: readthedocs